services:
  traefik:
    image: traefik:${TRAEFIK_TAG-latest}
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      coinmunity:
        aliases:
          - auth.localhost
          - admin.auth.localhost

  logto:
    image: svhd/logto:${LOGTO_TAG-latest}
    container_name: logto
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - TRUST_PROXY=true
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://${LOGTO_DB_USER}:${LOGTO_DB_PASS}@${LOGTO_DB_HOST}:${LOGTO_DB_PORT}/${LOGTO_DB_NAME}
      - ENDPOINT=${LOGTO_ENDPOINT-http://auth.localhost}
      - ADMIN_ENDPOINT=${LOGTO_ADMIN_ENDPOINT-http://admin.auth.localhost}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logto.rule=Host(`auth.localhost`) || Host(`admin.auth.localhost`)"
      - "traefik.http.services.logto.loadbalancer.server.port=3001"
    networks:
      - coinmunity
    depends_on:
      postgres:
        condition: service_healthy
      traefik:
        condition: service_started

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    user: postgres
    env_file:
      - .env
    volumes:
      - ${PWD-.}/infrastructure/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - coinmunity

volumes:
  pg-data:
    name: coinmunity_pg_data

networks:
  coinmunity:
    driver: bridge